# suppress inspection "WrongPropertyKeyValueDelimiter" for whole file
# suppress inspection "WrongPropertyKeyValueDelimiter" for whole file
# suppress inspection "UnusedProperty" for whole file
DJXCTGW4WGZQ6AAAAAAAAAAAAA